services:
  postgres:
    image: postgres:15
    container_name: sucden_postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - sucden_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sucden
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sucden_db
    networks:
      - app-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sucden_app
    restart: unless-stopped
    working_dir: /var/www/html        # ← match backend Dockerfile WORKDIR
    volumes:
      - ./backend:/var/www/html       # ← mount to same path
    ports:
      - "8686:8686"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.dev
    command: >
      sh -c "
      composer install &&
      php artisan config:cache &&
      php artisan migrate --force &&
      php artisan octane:start --server=swoole --host=0.0.0.0 --port=8686
      "
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: sucden_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - app-network

volumes:
  sucden_pgdata:

networks:
  app-network:
    driver: bridge
